// FirstSDI.idl : type library source for ActiveX Control project.

// This file will be processed by the MIDL compiler tool to
// produce the type library (FirstSDI.tlb) that will become a resource in
// FirstSDI.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(067C9AC5-FA39-4320-A707-F0B71CB25492), version(1.0),
  control ]
library FirstSDILib
{
	importlib(STDOLE_TLB);

	//  Primary dispatch interface for CFirstSDICtrl
	[ 
		uuid(183635FF-37E7-40B6-A851-666EFF4BAD27)	
	]
	dispinterface _DFirstSDI
	{
		properties:
		methods:

			[id(DISPID_ABOUTBOX)] void AboutBox();
	};

	//  Event dispatch interface for CFirstSDICtrl

	[ 
		uuid(45D68F88-449B-412E-99C9-21A26AB3A08F)	
	]
	dispinterface _DFirstSDIEvents
	{
		properties:
			//  Event interface has no properties

		methods:
	};

	//  Class information for CFirstSDICtrl
	[
		uuid(EB718317-D19A-4143-A21D-C9837BB37E1D)
	]
	coclass FirstSDI
	{
		[default] dispinterface _DFirstSDI;
		[default, source] dispinterface _DFirstSDIEvents;
	};

};
